BulkyBook/BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public CategoryController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        }
        public IActionResult Index()
        {
            //var objCatogoryList = _db.Categories.ToList();
            //IEnumerable<Category> objCatogoryList = _db.Categories.ToList();

            IEnumerable<Category> objCatogoryList = _unitofwork.Category.GetAll();
            return View(objCatogoryList);
        }
        //////////////////////////////////////////////////////////////////////////////////////
        //GET
        public IActionResult Create()
        {
            //IEnumerable<Category> objCatogoryList = _db.Categories;
            //return View(objCatogoryList);
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                //To display custome errors
                //ModelState.AddModelError("CustomError","The DisplayOrder cannot exactly match the name");
                ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            }

            if (ModelState.IsValid)
            {
                _unitofwork.Category.Add(obj);
                _unitofwork.Save();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        /////////////////////////////////////////////////////////////////////////////////////////////
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitofwork.Category.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbsingle = _db.Categories.SingleOrDefault(u => u.Id == id);


            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            }

            if (ModelState.IsValid)
            {
                _unitofwork.Category.Update(obj);
                _unitofwork.Save();
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        /////////////////////////////////////////////////////////////////////////
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDbFirst = _unitofwork.Category.GetFirstOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeletePost(int? id)
        {
            var obj = _unitofwork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitofwork.Category.Remove(obj);
            _unitofwork.Save();
            TempData["success"] = "Category Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyBook/BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitofwork;
    

    public CompanyController(IUnitOfWork unitofwork)
    {
        _unitofwork = unitofwork;
        
    }

    public IActionResult Index()
    {
        

        //IEnumerable<Product> objProductList = _unitofwork.Product.GetAll();
        return View();
    }
    
    ///////// Change  public IActionResult Edit , as
    //GET
    public IActionResult Upsert(int? id)
    {
          Company  company = new();
           

        if (id == null || id == 0)
        {
            // Create Product


            //ViewBag.CategoryList = CategoryList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            //return View(product);
            return View(company);
        }
        else
        {
            company = _unitofwork.Company.GetFirstOrDefault(u => u.Id == id);
            // update Product
            return View(company);
        }

        
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Company obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {            

            if(obj.Id == 0)
            {
                _unitofwork.Company.Add(obj);
                TempData["success"] = "Company added Successfully";
            }
            else
            {
                _unitofwork.Company.Update(obj);
                TempData["success"] = "Company updated Successfully";
            }
            
            _unitofwork.Save();
            
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    


    #region APICalls
    [HttpGet]
    public IActionResult GetAll() 
    {
        var CompanyList = _unitofwork.Company.GetAll();
        return Json(new {data = CompanyList});
    }

    //POST
    [HttpDelete]
    //[ValidateAntiForgeryToken]
    public IActionResult Delete(int? id)
    {
        var obj = _unitofwork.Company.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting!"});
        }
       
        _unitofwork.Company.Remove(obj);
        _unitofwork.Save();
        
        return Json(new { success = true, message = "Deleted successfully"});
        
    }
    #endregion
}

BulkyBook/BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public CoverTypeController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        }
        public IActionResult Index()
        {
            

            IEnumerable<CoverType> objCoverTypeList = _unitofwork.CoverType.GetAll();
            return View(objCoverTypeList);
        }
        //////////////////////////////////////////////////////////////////////////////////////
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitofwork.CoverType.Add(obj);
                _unitofwork.Save();
                TempData["success"] = "CoverType Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        /////////////////////////////////////////////////////////////////////////////////////////////
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            
            var CoverTypeFromDbFirst = _unitofwork.CoverType.GetFirstOrDefault(u => u.Id == id);
            
            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitofwork.CoverType.Update(obj);
                _unitofwork.Save();
                TempData["success"] = "CoverType Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        /////////////////////////////////////////////////////////////////////////
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverTypeFromDbFirst = _unitofwork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeletePost(int? id)
        {
            var obj = _unitofwork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitofwork.CoverType.Remove(obj);
            _unitofwork.Save();
            TempData["success"] = "CoverType Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyBook/BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitofwork;
    private readonly IWebHostEnvironment _hostEnvironment;

    public ProductController(IUnitOfWork unitofwork, IWebHostEnvironment webhostEnvironment)
    {
        _unitofwork = unitofwork;
        _hostEnvironment = webhostEnvironment;
    }

    public IActionResult Index()
    {
        

        //IEnumerable<Product> objProductList = _unitofwork.Product.GetAll();
        return View();
    }
    
    ///////// Change  public IActionResult Edit , as
    //GET
    public IActionResult Upsert(int? id)
    {
        //Product product = new();
        //IEnumerable<SelectListItem> CategoryList = _unitofwork.Category.GetAll().Select
        //    ( u => new SelectListItem
        //    {
        //        Text = u.Name,
        //        Value = u.Id.ToString()
        //    });

        // IEnumerable<SelectListItem> CoverTypeList = _unitofwork.CoverType.GetAll().Select
        //     ( u => new SelectListItem
        //     {
        //         Text = u.Name,
        //         Value = u.Id.ToString()
        //     });

        ProductVM productVM = new()
        {
            Product = new(),
            CategoryList = _unitofwork.Category.GetAll().Select
            (i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
            CoverTypeList = _unitofwork.CoverType.GetAll().Select
            (i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            })
        };

        if (id == null || id == 0)
        {
            // Create Product


            //ViewBag.CategoryList = CategoryList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            //return View(product);
            return View(productVM);
        }
        else
        {
            productVM.Product = _unitofwork.Product.GetFirstOrDefault(u => u.Id == id);
            // update Product
            return View(productVM);
        }

        
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductVM obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if(file != null)
            {
                string filename = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"Images\products");
                var extension = Path.GetExtension(file.FileName);

                if(obj.Product.ImageUrl!= null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                    if(System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStreams = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.Product.ImageUrl = @"\Images\products\" + filename + extension;
            }

            if(obj.Product.Id == 0)
            {
                _unitofwork.Product.Add(obj.Product);
            }
            else
            {
                _unitofwork.Product.Update(obj.Product);
            }
            _unitofwork.Product.Add(obj.Product);
            _unitofwork.Save();
            TempData["success"] = "Product added Successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    /////////////////////////////////////////////////////////////////////////
    //GET
    //public IActionResult Delete(int? id)
    //{
    //    if (id == null || id == 0)
    //    {
    //        return NotFound();
    //    }
    //    var ProductFromDbFirst = _unitofwork.Product.GetFirstOrDefault(u => u.Id == id);

    //    if (ProductFromDbFirst == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(ProductFromDbFirst);
    //}

    ////POST
    //[HttpPost]
    //[ValidateAntiForgeryToken]

    //public IActionResult DeletePost(int? id)
    //{
    //    var obj = _unitofwork.Product.GetFirstOrDefault(u => u.Id == id);
    //    if (obj == null)
    //    {
    //        return NotFound();
    //    }
    //    _unitofwork.Product.Remove(obj);
    //    _unitofwork.Save();
    //    TempData["success"] = "Product Deleted Successfully";
    //    return RedirectToAction("Index");
    //}


    #region APICalls
    [HttpGet]
    public IActionResult GetAll() 
    {
        var ProductList = _unitofwork.Product.GetAll(includeProperties:"Category,CoverType");
        return Json(new {data = ProductList});
    }

    //POST
    [HttpDelete]
    //[ValidateAntiForgeryToken]
    public IActionResult Delete(int? id)
    {
        var obj = _unitofwork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting!"});
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }

        _unitofwork.Product.Remove(obj);
        _unitofwork.Save();
        
        return Json(new { success = true, message = "Deleted successfully"});
        
    }
    #endregion
}

BulkyBook/BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.2/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>

        @*<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
        <li class="nav-item">
        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
        </li>*@

        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" style="color:azure">
                    <img src="~/Images/NavBarBrand/R.png" width="45px" height="45px"/>
                    <i class="fa fa-book fw-bold text-light">BulkyBook</i>
                    </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index" style="color:white">Home</a>
                        </li>


                        @*<li class="nav-item">
                        <a class="nav-link" style="color:white">About</a>
                        </li>*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                               role="button" aria-haspopup="true" aria-expanded="false" style="color:white; ">Content Management</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>

                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Order" asp-area="Admin" style="color:aliceblue">
                                Manage Order
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Cart" asp-area="Customer" style="color:aliceblue">
                                <i class="bi bi-cart"></i>
                            </a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
        </nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">

        </li>
        <li class="nav-item">

        </li>
        </ul>
        </div>
        </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/jyam17t9gxv1rg2a9z1pku3y5w2kpwlvpa6sxoxvznw8pn97/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBook/BulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @*<h2 style="text-align:center; background-color:none; color:dodgerblue">@TempData["success"]</h2>*@

    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}


@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @*<h2 style="text-align:center; background-color:none; color:dodgerblue">@TempData["error"]</h2>*@

    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}